<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Bindings[
	<!ELEMENT Bindings (Binding*)>
	<!ELEMENT Binding (Name, FilterSet, Target)>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT FilterSet (Filter*, FilterSet*)*>
	<!ELEMENT Filter (#PCDATA)>
	<!ELEMENT Target (#PCDATA)>
	<!ATTLIST Binding type (PALETTE|GRAPHICS) #REQUIRED>
	<!ATTLIST FilterSet method (AND|NAND|OR|NOR|XOR) #REQUIRED>
	<!ATTLIST Filter type (MAGIC|FILEEXT) #REQUIRED format (DEC|HEX|STR) #REQUIRED>
	<!ATTLIST Target type (LUA|METHOD) #REQUIRED>
]
>
<Bindings>
	<Binding type="GRAPHICS">
		<Name>NCGR and NCBR Files</Name>
		<FilterSet method="AND">
			<Filter format="STR" type="MAGIC">RGCN</Filter>
		</FilterSet>
		<Target type="METHOD">loadFileAsNCGR</Target>
	</Binding>
	<Binding type="PALETTE">
		<Name>NCLR files</Name>
		<FilterSet method="AND">
			<Filter format="STR" type="MAGIC">RLCN</Filter>
		</FilterSet>
		<Target type="METHOD">loadFileAsNCLR</Target>
	</Binding>
</Bindings>
